# Generated by Django 5.0.6 on 2024-06-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_registrationcount_client_user_and_more'),
    ]

    operations = [
    ]
