# Generated by Django 5.0.6 on 2024-06-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20240626_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
